# Feign Setting
feign:
  hystrix:
    enabled: true
# Hystrix Setting
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
  # Threadpool Setting
  threadpool:
    default:
      coreSize: 80
# Spring Setting
spring:
  # Data Info Source Setting
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dataintegration?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

# Mybatis Camel Case Setting
mybatis:
  configuration:
    map-underscore-to-camel-case: true

# Page Helper Setting
pagehelper:
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
  params: count=countSql
  
title: value
