server:
  port: 8080
spring:
  application:
    name: zuul
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    healthcheck:
      enabled: true